### ISSUE TITLE
Retroalimentación

### ISSUE THREAD

**Issue by Guirdo** [Gagod98/Pinterest_Clone#1]
Para que puedas cambiar el color del borde de un elemento `<input>`, además de modificar la propiedad `border` tienes que modificar el borde de este cuando se le hace focus. Checa el siguiente código:

```css
.barra-de-busqueda{
    /* el resto de tu código */
    border: 2px solid green;
}

.barra-de-busqueda:focus {
  outline: none;
  border:2px solid green;/*here change the color*/
}
```
